[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "h5py>=3.13.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "plotly>=6.1.0",
    "torch>=2.6.0",
]
